export type PaperKind = "paper" | "explainer";

export type Paper = {
  id: string;
  title: string;
  authors: string[];
  year: number;
  venue: string;
  url: string;
  kind: PaperKind;
  topics: string[];
  genes?: string[];
  summary: string;
};

/** Curated lookup shelf. Ranking is applied at query time; this is just the card catalogue. */
export const PAPERS: Paper[] = [
  {
    id: "dejesus-2015-transit",
    title: "TRANSIT — a software tool for Himar1 TnSeq analysis",
    authors: ["DeJesus MA", "Ambadipudi C", "Baker R", "Sassetti C", "Ioerger TR"],
    year: 2015,
    venue: "PLoS Computational Biology",
    url: "https://pubmed.ncbi.nlm.nih.gov/26447887/",
    kind: "paper",
    topics: ["tb-tnseq-transit", "tb-essentiality", "TnSeq", "TRANSIT", "Himar1", "HMM"],
    summary: "The Ioerger/Sassetti GUI and methods (Gumbel, HMM, resampling) for calling essentiality from Himar1 insertion counts.",
  },
  {
    id: "dejesus-2017-mbio",
    title: "Comprehensive essentiality analysis of the M. tuberculosis genome via saturating transposon mutagenesis",
    authors: ["DeJesus MA", "Gerrick ER", "Xu W", "Park SW", "Long JE", "Boutte CC", "Rubin EJ", "Schnappinger D", "Ehrt S", "Fortune SM", "Sassetti CM", "Ioerger TR"],
    year: 2017,
    venue: "mBio",
    url: "https://pubmed.ncbi.nlm.nih.gov/28096490/",
    kind: "paper",
    topics: ["tb-tnseq-transit", "tb-essentiality", "tb-crispri-hypomorphs", "H37Rv"],
    summary: "Saturating Himar1 library; the genome-wide essentiality call-set most TRANSIT tutorials still orbit.",
  },
  {
    id: "dejesus-2013-hmm",
    title: "A hidden Markov model for identifying essential and growth-defect regions in bacterial genomes from transposon insertion sequencing data",
    authors: ["DeJesus MA", "Ioerger TR"],
    year: 2013,
    venue: "BMC Bioinformatics",
    url: "https://pubmed.ncbi.nlm.nih.gov/24112407/",
    kind: "paper",
    topics: ["tb-tnseq-transit", "tb-essentiality", "HMM"],
    summary: "HMM along the chromosome so domain-level essentiality is not forced into one gene box.",
  },
  {
    id: "dejesus-2013-bayes",
    title: "Bayesian analysis of gene essentiality based on sequencing of transposon insertion libraries",
    authors: ["DeJesus MA", "Zhang YJ", "Sassetti CM", "Rubin EJ", "Sacchettini JC", "Ioerger TR"],
    year: 2013,
    venue: "Bioinformatics",
    url: "https://doi.org/10.1093/bioinformatics/btt043",
    kind: "paper",
    topics: ["tb-tnseq-transit", "tb-essentiality", "stats-bayesian", "Gumbel"],
    summary: "Gumbel / Bayesian read of insertion counts: why a gene with unlucky TA sites is not automatically essential.",
  },
  {
    id: "ioerger-2022-mmb",
    title: "Analysis of gene essentiality from TnSeq data using TRANSIT",
    authors: ["Ioerger TR"],
    year: 2022,
    venue: "Methods in Molecular Biology",
    url: "https://pubmed.ncbi.nlm.nih.gov/34709629/",
    kind: "paper",
    topics: ["tb-tnseq-transit", "tb-essentiality", "TRANSIT"],
    summary: "The methods-chapter walkthrough: .wig files, saturation, and which TRANSIT method to reach for.",
  },
  {
    id: "griffin-2011-cholesterol",
    title: "High-resolution phenotypic profiling defines genes essential for mycobacterial growth and cholesterol catabolism",
    authors: ["Griffin JE", "Gawronski JD", "DeJesus MA", "Ioerger TR", "Akerley BJ", "Sassetti CM"],
    year: 2011,
    venue: "PLoS Pathogens",
    url: "https://pubmed.ncbi.nlm.nih.gov/21980272/",
    kind: "paper",
    topics: ["tb-tnseq-transit", "tb-essentiality", "tb-cholesterol-catabolism", "cholesterol", "prpRDC"],
    genes: ["prpD", "prpC", "prpR", "mce4"],
    summary: "Early Sassetti–Ioerger TnSeq: glycerol vs cholesterol, and why prpRDC shows up when propionate is the story.",
  },
  {
    id: "carey-2018-clinical-tnseq",
    title: "TnSeq of Mycobacterium tuberculosis clinical isolates reveals strain-specific antibiotic liabilities",
    authors: ["Carey AF", "Rock JM", "Krieger IV", "Chase MR", "Fernandez-Suarez M", "Gagneux S", "Sacchettini JC", "Ioerger TR", "Fortune SM"],
    year: 2018,
    venue: "PLoS Pathogens",
    url: "https://doi.org/10.1371/journal.ppat.1006939",
    kind: "paper",
    topics: ["tb-tnseq-transit", "tb-lineages-barcode", "tb-fitness-cost", "tb-cholesterol-catabolism", "lineage"],
    summary: "TnSeq is not only H37Rv. Clinical isolates have lineage-specific liabilities.",
  },
  {
    id: "dejesus-2017-nar",
    title: "Statistical analysis of genetic interactions in Tn-Seq data",
    authors: ["DeJesus MA", "Nambi S", "Smith CM", "Baker RE", "Sassetti CM", "Ioerger TR"],
    year: 2017,
    venue: "Nucleic Acids Research",
    url: "https://doi.org/10.1093/nar/gkx128",
    kind: "paper",
    topics: ["tb-tnseq-transit", "stats-lrt", "genetic interaction"],
    summary: "Double-mutant / interaction calls from TnSeq counts — resampling rather than a casual product of two essentials lists.",
  },
  {
    id: "ioerger-2013-pone-targets",
    title: "Identification of new drug targets and resistance mechanisms in Mycobacterium tuberculosis",
    authors: ["Ioerger TR", "O'Malley T", "Liao R", "Guinn KM", "Hickey MJ", "Mohaideen N", "Murphy KC", "Boshoff HI", "Mizrahi V", "Rubin EJ", "Sassetti CM", "Barry CE", "Sherman DR", "Parish T", "Sacchettini JC"],
    year: 2013,
    venue: "PLoS ONE",
    url: "https://doi.org/10.1371/journal.pone.0075216",
    kind: "paper",
    topics: ["tb-wgs-dst", "tb-rifampin", "tb-resistance", "WGS"],
    genes: ["rpoB", "katG", "pncA"],
    summary: "WGS of resistant isolates for targets and mechanisms — Ioerger with Parish, Rubin, Sassetti, Barry, Sherman, Sacchettini.",
  },
  {
    id: "sassetti-2003-nongene",
    title: "Genes required for mycobacterial growth defined by high density mutagenesis",
    authors: ["Sassetti CM", "Boyd DH", "Rubin EJ"],
    year: 2003,
    venue: "Molecular Microbiology",
    url: "https://pubmed.ncbi.nlm.nih.gov/12629610/",
    kind: "paper",
    topics: ["tb-essentiality", "tb-tnseq-transit", "TraSH"],
    summary: "Pre-TnSeq TraSH: Sassetti and Rubin defining the first genome-wide essentiality sketch.",
  },
  {
    id: "rock-2017-crispri",
    title: "Programmable transcriptional repression in mycobacteria using an orthogonal CRISPR interference platform",
    authors: ["Rock JM", "Hopkins FF", "Chavez A", "Diallo M", "Chase MR", "Gerrick ER", "Pritchard JR", "Church GM", "Rubin EJ", "Sassetti CM", "Schnappinger D", "Fortune SM"],
    year: 2017,
    venue: "Nature Microbiology",
    url: "https://pubmed.ncbi.nlm.nih.gov/28263307/",
    kind: "paper",
    topics: ["tb-crispri-hypomorphs", "tb-essentiality", "CRISPRi"],
    summary: "The mycobacterial CRISPRi platform: knock down essentials that TnSeq can only call ‘no insertions’.",
  },
  {
    id: "cole-1998-genome",
    title: "Deciphering the biology of Mycobacterium tuberculosis from the complete genome sequence",
    authors: ["Cole ST", "Brosch R", "Parkhill J", "Barry CE"],
    year: 1998,
    venue: "Nature",
    url: "https://doi.org/10.1038/31159",
    kind: "paper",
    topics: ["tb-organism", "wiki-mtb-organism", "H37Rv", "genome"],
    genes: ["rpoB", "katG", "pncA"],
    summary: "The H37Rv genome paper. Every later catalogue, TnSeq track, and rpoB numbering argument sits on this sequence.",
  },
  {
    id: "telenti-1993-rpob",
    title: "Detection of rifampicin-resistance mutations in Mycobacterium tuberculosis",
    authors: ["Telenti A", "Imboden P", "Marchesi F", "Cole S", "Colston MJ"],
    year: 1993,
    venue: "Lancet",
    url: "https://pubmed.ncbi.nlm.nih.gov/8094770/",
    kind: "paper",
    topics: ["tb-rifampin", "wiki-rpob-gene", "RRDR", "Xpert"],
    genes: ["rpoB"],
    summary: "The RRDR paper: rifampin resistance as a short stretch of rpoB, which is why Xpert only looks there.",
  },
  {
    id: "zhang-1992-katg",
    title: "The catalase-peroxidase gene and isoniazid resistance of Mycobacterium tuberculosis",
    authors: ["Zhang Y", "Heym B", "Allen B", "Young D", "Cole S"],
    year: 1992,
    venue: "Nature",
    url: "https://doi.org/10.1038/358591a0",
    kind: "paper",
    topics: ["tb-first-line", "wiki-katg-gene", "isoniazid", "tb-nat2-acetylator"],
    genes: ["katG", "inhA"],
    summary: "katG as the INH-activation story. Still the first gene you name when INH-R is the phenotype.",
  },
  {
    id: "walker-2015-wgs-dst",
    title: "Whole-genome sequencing for prediction of Mycobacterium tuberculosis drug susceptibility and resistance: a retrospective cohort study",
    authors: ["Walker TM", "Kohl TA", "Iqbal Z", "Niemann S", "Crook DW", "Supply P", "Peto TEA"],
    year: 2015,
    venue: "Lancet Infectious Diseases",
    url: "https://pubmed.ncbi.nlm.nih.gov/26116186/",
    kind: "paper",
    topics: ["tb-wgs-dst", "tb-pdst-versus-gdst", "gDST", "CRyPTIC"],
    genes: ["rpoB", "katG", "pncA", "gyrA"],
    summary: "WGS as DST in a real cohort: Walker, Niemann, Crook, Iqbal, Supply — the CRyPTIC-era argument.",
  },
  {
    id: "farhat-2013-natgenet",
    title: "Genomic analysis identifies targets of convergent positive selection in drug-resistant Mycobacterium tuberculosis",
    authors: ["Farhat MR", "Shapiro BJ", "Gagneux S", "Murray M"],
    year: 2013,
    venue: "Nature Genetics",
    url: "https://pubmed.ncbi.nlm.nih.gov/23995135/",
    kind: "paper",
    topics: ["tb-wgs-dst", "tb-fitness-cost", "tb-rifampin", "convergence"],
    genes: ["rpoB", "rpoC", "katG"],
    summary: "Convergent evolution as a resistance-gene finder. Compensatory rpoC lives in this family of papers.",
  },
  {
    id: "gagneux-2018-nrm",
    title: "Ecology and evolution of Mycobacterium tuberculosis",
    authors: ["Gagneux S"],
    year: 2018,
    venue: "Nature Reviews Microbiology",
    url: "https://doi.org/10.1038/nrmicro.2018.8",
    kind: "paper",
    topics: ["tb-lineages-barcode", "tb-organism", "lineage", "Beijing"],
    summary: "Lineages 1–4 as geography and ecology, not a strain-typing hobby.",
  },
  {
    id: "cryptic-2022-catalogue",
    title: "A data compendium associating the genomes of 12,289 Mycobacterium tuberculosis isolates with quantitative resistance phenotypes",
    authors: ["The CRyPTIC Consortium"],
    year: 2022,
    venue: "PLOS Biology",
    url: "https://doi.org/10.1371/journal.pbio.3001721",
    kind: "paper",
    topics: ["tb-wgs-dst", "tb-pdst-versus-gdst", "MIC", "catalogue"],
    genes: ["rpoB", "katG", "pncA", "gyrA", "embB"],
    summary: "CRyPTIC: genomes plus MICs at a scale that makes a mutation catalogue a statistical object.",
  },
  {
    id: "who-catalogue-2021",
    title: "Catalogue of mutations in Mycobacterium tuberculosis complex and their association with drug resistance",
    authors: ["World Health Organization"],
    year: 2021,
    venue: "WHO",
    url: "https://www.who.int/publications/i/item/9789240028173",
    kind: "paper",
    topics: ["tb-wgs-dst", "tb-rifampin", "tb-pdst-versus-gdst", "WHO"],
    genes: ["rpoB", "katG", "pncA", "gyrA", "rrs", "embB"],
    summary: "The public grading layer: associated / not associated / uncertain. Tools are not this catalogue.",
  },
  {
    id: "ramakrishnan-2012-granuloma",
    title: "Revisiting the role of the granuloma in tuberculosis",
    authors: ["Ramakrishnan L"],
    year: 2012,
    venue: "Nature Reviews Immunology",
    url: "https://doi.org/10.1038/nri3211",
    kind: "paper",
    topics: ["tb-granuloma", "tb-primary-postprimary", "caseum"],
    summary: "The granuloma as a living, spatially organised programme, not a binary prison.",
  },
  {
    id: "russell-2007-tubercle",
    title: "Who puts the tubercle in tuberculosis?",
    authors: ["Russell DG"],
    year: 2007,
    venue: "Nature Reviews Microbiology",
    url: "https://doi.org/10.1038/nrmicro1538",
    kind: "paper",
    topics: ["tb-granuloma", "tb-innate-adaptive", "macrophage"],
    summary: "Lesion architecture and the macrophage as the site of the argument, not a footnote.",
  },
  {
    id: "wilks-1938",
    title: "The large-sample distribution of the likelihood ratio for testing composite hypotheses",
    authors: ["Wilks SS"],
    year: 1938,
    venue: "Annals of Mathematical Statistics",
    url: "https://doi.org/10.1214/aoms/1177732360",
    kind: "paper",
    topics: ["stats-lrt", "wiki-wilks", "stats-likelihood", "chi-square"],
    summary: "Λ → χ² under regularity. The nested-model license, and the reason boundaries are a headache.",
  },
  {
    id: "benjamini-1995-fdr",
    title: "Controlling the false discovery rate: a practical and powerful approach to multiple testing",
    authors: ["Benjamini Y", "Hochberg Y"],
    year: 1995,
    venue: "JRSS-B",
    url: "https://doi.org/10.1111/j.2517-6161.1995.tb02031.x",
    kind: "paper",
    topics: ["stats-fdr", "wiki-bh-procedure", "stats-multiple-testing", "q-value"],
    summary: "BH as a procedure, not a vibe. GWAS and TnSeq hit lists live here.",
  },
  {
    id: "efron-1979-bootstrap",
    title: "Bootstrap methods: another look at the jackknife",
    authors: ["Efron B"],
    year: 1979,
    venue: "Annals of Statistics",
    url: "https://doi.org/10.1214/aos/1176344552",
    kind: "paper",
    topics: ["stats-bootstrap", "stats-permutation", "standard error"],
    summary: "Resample the sample you have. TRANSIT’s resampling test is this idea with insertion counts.",
  },
  {
    id: "gelman-hill-data-analysis",
    title: "Data Analysis Using Regression and Multilevel/Hierarchical Models (book site)",
    authors: ["Gelman A", "Hill J"],
    year: 2007,
    venue: "Cambridge University Press (companion)",
    url: "http://www.stat.columbia.edu/~gelman/arm/",
    kind: "explainer",
    topics: ["stats-hierarchical", "stats-bayesian", "partial pooling"],
    summary: "The hierarchical-models teaching site. Shrinkage without pretending τ is a dummy variable.",
  },
  {
    id: "openstax-stats",
    title: "Introductory Statistics — OpenStax",
    authors: ["OpenStax"],
    year: 2023,
    venue: "OpenStax",
    url: "https://openstax.org/details/books/introductory-statistics",
    kind: "explainer",
    topics: ["stats-probability-axioms", "stats-normal-clt", "stats-hypothesis-testing", "stats-foundations"],
    summary: "CC textbook for the first definitions: probability, CLT, tests. Not a TB methods paper.",
  },
  {
    id: "wiki-tuberculosis",
    title: "Tuberculosis — Wikipedia",
    authors: ["Wikipedia contributors"],
    year: 2026,
    venue: "Wikipedia",
    url: "https://en.wikipedia.org/wiki/Tuberculosis",
    kind: "explainer",
    topics: ["wiki-tuberculosis", "tb-organism", "tb-diagnosis", "tb-granuloma"],
    summary: "The encyclopedia card. Use it for names, then come back to a plate for the actual argument.",
  },
  {
    id: "wiki-lrt",
    title: "Likelihood-ratio test — Wikipedia",
    authors: ["Wikipedia contributors"],
    year: 2026,
    venue: "Wikipedia",
    url: "https://en.wikipedia.org/wiki/Likelihood-ratio_test",
    kind: "explainer",
    topics: ["stats-lrt", "wiki-wilks", "stats-likelihood"],
    summary: "Glossary-level Wilks. The studio lesson is the nested-pizza version.",
  },
  {
    id: "gfg-bayes",
    title: "Bayes’ theorem — GeeksforGeeks",
    authors: ["GeeksforGeeks"],
    year: 2024,
    venue: "GeeksforGeeks",
    url: "https://www.geeksforgeeks.org/bayes-theorem/",
    kind: "explainer",
    topics: ["stats-bayesian", "stats-conditional-probability", "wiki-bayes-theorem"],
    summary: "A first-pass explainer for P(A|B). Not a substitute for a prior you have to defend.",
  },
  {
    id: "gfg-hypothesis",
    title: "Understanding hypothesis testing — GeeksforGeeks",
    authors: ["GeeksforGeeks"],
    year: 2024,
    venue: "GeeksforGeeks",
    url: "https://www.geeksforgeeks.org/hypothesis-testing/",
    kind: "explainer",
    topics: ["stats-hypothesis-testing", "wiki-pvalue", "stats-pvalue-versus-posterior"],
    summary: "Null, alternative, α. Then read the p-value-is-not-a-posterior plate.",
  },
  {
    id: "transit-docs",
    title: "TRANSIT documentation",
    authors: ["Ioerger TR", "DeJesus MA"],
    year: 2024,
    venue: "ReadTheDocs",
    url: "https://transit.readthedocs.io/en/stable/transit_overview.html",
    kind: "explainer",
    topics: ["tb-tnseq-transit", "tb-essentiality", "TRANSIT", "wig"],
    summary: "The software manual: Gumbel vs HMM vs resampling, Himar1 vs Tn5, and how to run it.",
  },
  {
    id: "ncbi-bookshelf-tb",
    title: "Tuberculosis — NCBI Bookshelf (Harrison’s / related open chapters)",
    authors: ["NCBI Bookshelf"],
    year: 2024,
    venue: "NCBI Bookshelf",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK441916/",
    kind: "explainer",
    topics: ["tb-diagnosis", "tb-first-line", "wiki-tuberculosis"],
    summary: "Open clinical-chapter style notes. Not a mutation catalogue.",
  },
  {
    id: "pandey-2008-cholesterol",
    title: "Mycobacterial persistence requires the utilization of host cholesterol",
    authors: ["Pandey AK", "Sassetti CM"],
    year: 2008,
    venue: "Proceedings of the National Academy of Sciences",
    url: "https://pubmed.ncbi.nlm.nih.gov/18334637/",
    kind: "paper",
    topics: ["tb-cholesterol-catabolism", "tb-essentiality", "mce4", "persistence"],
    genes: ["mce4"],
    summary: "Sassetti: Mce4 and cholesterol utilization as a persistence story — the co-author ring when you asked about cholesterol.",
  },
  {
    id: "huang-2002-nat2",
    title: "Genetic polymorphisms of drug-metabolizing enzymes and susceptibility to antituberculosis drug-induced hepatitis",
    authors: ["Huang YS", "Chern HD", "Su WJ", "Wu JC", "Lai SL", "Yang SY", "Chang FY", "Lee SD"],
    year: 2002,
    venue: "Hepatology",
    url: "https://pubmed.ncbi.nlm.nih.gov/11915035/",
    kind: "paper",
    topics: ["tb-nat2-acetylator", "tb-hepatotoxicity", "isoniazid", "NAT2"],
    genes: ["NAT2"],
    summary: "Host pharmacogenetics around INH injury. Slow acetylator / NAT2 is a person, not a bacillus catalogue grade.",
  },
  {
    id: "wiki-nat2",
    title: "NAT2 — Wikipedia",
    authors: ["Wikipedia contributors"],
    year: 2026,
    venue: "Wikipedia",
    url: "https://en.wikipedia.org/wiki/NAT2",
    kind: "explainer",
    topics: ["tb-nat2-acetylator", "NAT2", "acetylator"],
    summary: "The encyclopedia card for N-acetyltransferase 2. Slow vs rapid is host pharmacogenetics.",
  },
  {
    id: "wiki-cholesterol",
    title: "Cholesterol — Wikipedia",
    authors: ["Wikipedia contributors"],
    year: 2026,
    venue: "Wikipedia",
    url: "https://en.wikipedia.org/wiki/Cholesterol",
    kind: "explainer",
    topics: ["tb-cholesterol-catabolism", "cholesterol"],
    summary: "The sterol encyclopedia page. The Mtb pathway evidence is Griffin / TRANSIT, not this card.",
  },
];
